{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b2dc8066-ec21-4aac-9f57-81adbdedbb66",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "test_ST_RD_01_insert_card_when_not_idle (__main__.TestStateTransitions.test_ST_RD_01_insert_card_when_not_idle)\n",
      "RAINY: Inserting a card when machine is not IDLE raises RuntimeError. ... \u001b[32mok\u001b[0m\n",
      "test_ST_RD_02_enter_pin_when_idle (__main__.TestStateTransitions.test_ST_RD_02_enter_pin_when_idle)\n",
      "RAINY: Entering PIN when IDLE raises RuntimeError. ... \u001b[32mok\u001b[0m\n",
      "test_ST_RD_03_enter_pin_when_authenticated (__main__.TestStateTransitions.test_ST_RD_03_enter_pin_when_authenticated)\n",
      "RAINY: Entering PIN when AUTHENTICATED raises RuntimeError. ... \u001b[32mok\u001b[0m\n",
      "test_ST_RD_04_eject_when_idle (__main__.TestStateTransitions.test_ST_RD_04_eject_when_idle)\n",
      "RAINY: Ejecting when no card inserted raises RuntimeError. ... \u001b[32mok\u001b[0m\n",
      "test_ST_RD_05_insert_pre_blocked_card (__main__.TestStateTransitions.test_ST_RD_05_insert_pre_blocked_card)\n",
      "RAINY: Inserting a card that is already blocked → CARD_BLOCKED immediately. ... \u001b[32mok\u001b[0m\n",
      "test_ST_RD_06_withdraw_when_not_authenticated (__main__.TestStateTransitions.test_ST_RD_06_withdraw_when_not_authenticated)\n",
      "RAINY: Withdrawal when machine is IDLE raises RuntimeError. ... \u001b[32mok\u001b[0m\n",
      "test_ST_RD_07_check_balance_when_not_authenticated (__main__.TestStateTransitions.test_ST_RD_07_check_balance_when_not_authenticated)\n",
      "RAINY: check_balance when machine is IDLE raises RuntimeError. ... \u001b[32mok\u001b[0m\n",
      "test_ST_SD_01_idle_to_awaiting_pin (__main__.TestStateTransitions.test_ST_SD_01_idle_to_awaiting_pin)\n",
      "SUNNY: Insert a valid card → machine moves to AWAITING_PIN. ... \u001b[32mok\u001b[0m\n",
      "test_ST_SD_02_awaiting_pin_to_authenticated (__main__.TestStateTransitions.test_ST_SD_02_awaiting_pin_to_authenticated)\n",
      "SUNNY: Correct PIN → machine moves to AUTHENTICATED. ... \u001b[32mok\u001b[0m\n",
      "test_ST_SD_03_authenticated_to_idle (__main__.TestStateTransitions.test_ST_SD_03_authenticated_to_idle)\n",
      "SUNNY: Eject after authentication → machine returns to IDLE. ... \u001b[32mok\u001b[0m\n",
      "test_ST_SD_04_card_blocked_to_idle (__main__.TestStateTransitions.test_ST_SD_04_card_blocked_to_idle)\n",
      "SUNNY: Eject a blocked card → machine returns to IDLE. ... \u001b[32mok\u001b[0m\n",
      "test_ST_SD_05_re_insert_after_session (__main__.TestStateTransitions.test_ST_SD_05_re_insert_after_session)\n",
      "SUNNY: Full session completes; a second card can be inserted. ... \u001b[32mok\u001b[0m\n",
      "test_CF_RD_01_unknown_card (__main__.TestControlFlow.test_CF_RD_01_unknown_card)\n",
      "RAINY: insert_card with unrecognised card — machine stays IDLE. ... \u001b[32mok\u001b[0m\n",
      "test_CF_RD_02_three_wrong_pins_blocks_card (__main__.TestControlFlow.test_CF_RD_02_three_wrong_pins_blocks_card)\n",
      "RAINY: Three consecutive wrong PINs → CARD_BLOCKED. ... \u001b[32mok\u001b[0m\n",
      "test_CF_RD_03_withdraw_non_numeric_string (__main__.TestControlFlow.test_CF_RD_03_withdraw_non_numeric_string)\n",
      "RAINY: Non-numeric withdrawal → invalid-amount branch. ... \u001b[32mok\u001b[0m\n",
      "test_CF_RD_04_withdraw_negative_amount (__main__.TestControlFlow.test_CF_RD_04_withdraw_negative_amount)\n",
      "RAINY: Negative amount → guard branch fires. ... \u001b[32mok\u001b[0m\n",
      "test_CF_RD_05_withdraw_zero (__main__.TestControlFlow.test_CF_RD_05_withdraw_zero)\n",
      "RAINY: Zero amount → guard branch fires. ... \u001b[32mok\u001b[0m\n",
      "test_CF_RD_06_withdraw_over_limit (__main__.TestControlFlow.test_CF_RD_06_withdraw_over_limit)\n",
      "RAINY: Amount exceeds single-transaction cap ($10,000). ... \u001b[32mok\u001b[0m\n",
      "test_CF_RD_07_withdraw_more_than_atm_cash (__main__.TestControlFlow.test_CF_RD_07_withdraw_more_than_atm_cash)\n",
      "RAINY: ATM has less cash than requested — ATM-cash guard fires. ... \u001b[32mok\u001b[0m\n",
      "test_CF_RD_08_atm_completely_empty (__main__.TestControlFlow.test_CF_RD_08_atm_completely_empty)\n",
      "RAINY: ATM has zero cash — out-of-cash guard fires. ... \u001b[32mok\u001b[0m\n",
      "test_CF_RD_09_withdraw_more_than_account_balance (__main__.TestControlFlow.test_CF_RD_09_withdraw_more_than_account_balance)\n",
      "RAINY: Requested amount exceeds account balance — balance guard fires. ... \u001b[32mok\u001b[0m\n",
      "test_CF_RD_10_withdraw_non_numeric_none (__main__.TestControlFlow.test_CF_RD_10_withdraw_non_numeric_none)\n",
      "RAINY: None passed as amount — handled gracefully (no crash). ... \u001b[32mok\u001b[0m\n",
      "test_CF_SD_01_withdraw_exact_balance (__main__.TestControlFlow.test_CF_SD_01_withdraw_exact_balance)\n",
      "SUNNY: Withdraw entire account balance — both checks pass. ... \u001b[32mok\u001b[0m\n",
      "test_CF_SD_02_withdraw_partial_balance (__main__.TestControlFlow.test_CF_SD_02_withdraw_partial_balance)\n",
      "SUNNY: Partial withdrawal — account still has funds remaining. ... \u001b[32mok\u001b[0m\n",
      "test_CF_SD_03_check_balance_branch (__main__.TestControlFlow.test_CF_SD_03_check_balance_branch)\n",
      "SUNNY: check_balance returns correct value (exercises the success branch). ... \u001b[32mok\u001b[0m\n",
      "test_CF_SD_04_one_wrong_pin_then_correct (__main__.TestControlFlow.test_CF_SD_04_one_wrong_pin_then_correct)\n",
      "SUNNY: One wrong PIN (partial-fail branch) then correct PIN. ... \u001b[32mok\u001b[0m\n",
      "test_CF_SD_05_two_wrong_then_correct (__main__.TestControlFlow.test_CF_SD_05_two_wrong_then_correct)\n",
      "SUNNY: Two wrong PINs (1 remaining branch) then correct PIN. ... \u001b[32mok\u001b[0m\n",
      "test_DF_RD_01_balance_unchanged_after_failed_withdrawal (__main__.TestDataFlow.test_DF_RD_01_balance_unchanged_after_failed_withdrawal)\n",
      "RAINY: A failed withdrawal must NOT mutate account.balance. ... \u001b[32mok\u001b[0m\n",
      "test_DF_RD_02_atm_cash_unchanged_after_failed_withdrawal (__main__.TestDataFlow.test_DF_RD_02_atm_cash_unchanged_after_failed_withdrawal)\n",
      "RAINY: A failed withdrawal must NOT mutate atm_cash. ... \u001b[32mok\u001b[0m\n",
      "test_DF_RD_03_receipt_remains_none_after_failed_withdrawal (__main__.TestDataFlow.test_DF_RD_03_receipt_remains_none_after_failed_withdrawal)\n",
      "RAINY: A failed withdrawal must NOT overwrite last_receipt. ... \u001b[32mok\u001b[0m\n",
      "test_DF_RD_04_receipt_preserved_after_second_withdrawal_fails (__main__.TestDataFlow.test_DF_RD_04_receipt_preserved_after_second_withdrawal_fails)\n",
      "RAINY: Good receipt followed by a failed withdrawal keeps the good receipt. ... \u001b[32mok\u001b[0m\n",
      "test_DF_RD_05_pin_attempts_accumulate_to_block (__main__.TestDataFlow.test_DF_RD_05_pin_attempts_accumulate_to_block)\n",
      "RAINY: pin_attempts increments correctly across all 3 failed attempts. ... \u001b[32mok\u001b[0m\n",
      "test_DF_RD_06_account_created_with_invalid_balance_raises (__main__.TestDataFlow.test_DF_RD_06_account_created_with_invalid_balance_raises)\n",
      "RAINY: Account.__init__ rejects negative balance — data validated at definition. ... \u001b[32mok\u001b[0m\n",
      "test_DF_RD_07_atm_created_with_invalid_cash_raises (__main__.TestDataFlow.test_DF_RD_07_atm_created_with_invalid_cash_raises)\n",
      "RAINY: ATM.__init__ rejects negative cash — data validated at definition. ... \u001b[32mok\u001b[0m\n",
      "test_DF_RD_08_insert_card_empty_string_raises (__main__.TestDataFlow.test_DF_RD_08_insert_card_empty_string_raises)\n",
      "RAINY: insert_card with empty string raises ValueError before state change. ... \u001b[32mok\u001b[0m\n",
      "test_DF_RD_09_enter_pin_none_raises (__main__.TestDataFlow.test_DF_RD_09_enter_pin_none_raises)\n",
      "RAINY: enter_pin(None) raises ValueError — input validated at entry point. ... \u001b[32mok\u001b[0m\n",
      "test_DF_SD_01_balance_defined_and_read (__main__.TestDataFlow.test_DF_SD_01_balance_defined_and_read)\n",
      "SUNNY: account.balance is defined on creation; readable via check_balance. ... \u001b[32mok\u001b[0m\n",
      "test_DF_SD_02_balance_defined_mutated_used (__main__.TestDataFlow.test_DF_SD_02_balance_defined_mutated_used)\n",
      "SUNNY: account.balance define → withdraw mutates it → check_balance reads updated value. ... \u001b[32mok\u001b[0m\n",
      "test_DF_SD_03_atm_cash_decreases_after_withdrawal (__main__.TestDataFlow.test_DF_SD_03_atm_cash_decreases_after_withdrawal)\n",
      "SUNNY: atm_cash defined at init; used and killed by withdraw. ... \u001b[32mok\u001b[0m\n",
      "test_DF_SD_04_receipt_defined_by_withdrawal (__main__.TestDataFlow.test_DF_SD_04_receipt_defined_by_withdrawal)\n",
      "SUNNY: last_receipt is None before first withdrawal; defined after it. ... \u001b[32mok\u001b[0m\n",
      "test_DF_SD_05_receipt_redefined_on_second_withdrawal (__main__.TestDataFlow.test_DF_SD_05_receipt_redefined_on_second_withdrawal)\n",
      "SUNNY: Second withdrawal kills the old receipt and defines a new one. ... \u001b[32mok\u001b[0m\n",
      "test_DF_SD_06_pin_attempts_reset_on_insert (__main__.TestDataFlow.test_DF_SD_06_pin_attempts_reset_on_insert)\n",
      "SUNNY: pin_attempts defined as 0 at insert_card (fresh session). ... \u001b[32mok\u001b[0m\n",
      "test_DF_SD_07_pin_attempts_increment_then_reset_on_success (__main__.TestDataFlow.test_DF_SD_07_pin_attempts_increment_then_reset_on_success)\n",
      "SUNNY: pin_attempts increments on wrong PIN; killed (reset to 0) on correct PIN. ... \u001b[32mok\u001b[0m\n",
      "test_DF_SD_08_multiple_withdrawals_accumulate_deductions (__main__.TestDataFlow.test_DF_SD_08_multiple_withdrawals_accumulate_deductions)\n",
      "SUNNY: Sequential withdrawals compound the balance mutation correctly. ... \u001b[32mok\u001b[0m\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 44 tests in 0.022s\n",
      "\n",
      "\u001b[32mOK\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "  ATM TESTING DEMO — State Transitions / Control Flow / Data Flow\n",
      "======================================================================\n",
      "\n",
      "\n",
      "======================================================================\n",
      "  RESULTS: 44/44 tests passed\n",
      "  ALL TESTS PASSED\n",
      "======================================================================\n",
      "Welcome to the ATM!\n",
      "----------------------------------------\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Please insert your card (enter card number):  1111\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Card accepted. Please enter your PIN (3 attempts allowed).\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Please enter your PIN:  1234\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "PIN accepted. Welcome, Emad Fattah.\n",
      "Your balance is: $2,500.00\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "\n",
    "Student: Emad Fattah \n",
    "Instructor: Randall Granier\n",
    "Class: MSSE 640 \n",
    "Week 7: Vibe Coding Mini-Assignment #3. State-Transitions/Control Flow Testing\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "ATM Testing Demo — Python\n",
    "=========================\n",
    "Demonstrates three testing disciplines applied to a simple ATM state machine:\n",
    "\n",
    "  1. State Transition Testing  — every valid and invalid state change is exercised\n",
    "  2. Control Flow Testing      — every branch / conditional path is covered\n",
    "  3. Data Flow Testing         — variables are traced from definition → use → kill\n",
    "\n",
    "Sunny Day scenarios: the happy path (things work as expected)\n",
    "Rainy Day scenarios: error paths, boundary conditions, and guard failures\n",
    "\n",
    "Run with:\n",
    "    python atm_testing_demo.py\n",
    "\"\"\"\n",
    "\n",
    "import unittest\n",
    "from datetime import datetime\n",
    "from typing import Optional\n",
    "\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "# DOMAIN MODEL\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "\n",
    "class AtmState:\n",
    "    IDLE = \"IDLE\"\n",
    "    AWAITING_PIN = \"AWAITING_PIN\"\n",
    "    AUTHENTICATED = \"AUTHENTICATED\"\n",
    "    CARD_BLOCKED = \"CARD_BLOCKED\"\n",
    "\n",
    "\n",
    "class Account:\n",
    "    \"\"\"Represents a bank account linked to a card.\"\"\"\n",
    "\n",
    "    def __init__(self, card_number: str, pin: str, holder_name: str, balance: float):\n",
    "        if not card_number or not isinstance(card_number, str):\n",
    "            raise ValueError(\"card_number must be a non-empty string\")\n",
    "        if not pin or not isinstance(pin, str):\n",
    "            raise ValueError(\"pin must be a non-empty string\")\n",
    "        if not holder_name or not isinstance(holder_name, str):\n",
    "            raise ValueError(\"holder_name must be a non-empty string\")\n",
    "        if not isinstance(balance, (int, float)) or balance < 0:\n",
    "            raise ValueError(\"balance must be a non-negative number\")\n",
    "\n",
    "        self.card_number: str = card_number\n",
    "        self.pin: str = pin\n",
    "        self.holder_name: str = holder_name\n",
    "        self.balance: float = round(float(balance), 2)\n",
    "        self.is_blocked: bool = False\n",
    "\n",
    "\n",
    "class ATM:\n",
    "    \"\"\"\n",
    "    ATM state machine.\n",
    "\n",
    "    States:\n",
    "        IDLE           → insert a valid card  → AWAITING_PIN\n",
    "        AWAITING_PIN   → correct PIN          → AUTHENTICATED\n",
    "        AWAITING_PIN   → 3 wrong PINs         → CARD_BLOCKED\n",
    "        AUTHENTICATED  → eject card           → IDLE\n",
    "        CARD_BLOCKED   → eject card           → IDLE\n",
    "    \"\"\"\n",
    "\n",
    "    MAX_PIN_ATTEMPTS = 3\n",
    "    MAX_WITHDRAWAL = 10_000.0\n",
    "\n",
    "    def __init__(self, atm_cash: float = 10_000.0):\n",
    "        if not isinstance(atm_cash, (int, float)) or atm_cash < 0:\n",
    "            raise ValueError(\"atm_cash must be a non-negative number\")\n",
    "\n",
    "        self._accounts: dict[str, Account] = {}\n",
    "        self._state: str = AtmState.IDLE\n",
    "        self._atm_cash: float = round(float(atm_cash), 2)\n",
    "        self._active_card: Optional[str] = None\n",
    "        self._pin_attempts: int = 0\n",
    "        self.last_receipt: Optional[str] = None\n",
    "\n",
    "    # ── Registration ──────────────────────────────────────────────────────────\n",
    "\n",
    "    def register_account(self, account: Account) -> None:\n",
    "        \"\"\"Add an account to this ATM's known cards.\"\"\"\n",
    "        if not isinstance(account, Account):\n",
    "            raise TypeError(\"account must be an Account instance\")\n",
    "        self._accounts[account.card_number] = account\n",
    "\n",
    "    # ── Read-only properties ──────────────────────────────────────────────────\n",
    "\n",
    "    @property\n",
    "    def state(self) -> str:\n",
    "        return self._state\n",
    "\n",
    "    @property\n",
    "    def atm_cash(self) -> float:\n",
    "        return self._atm_cash\n",
    "\n",
    "    @property\n",
    "    def pin_attempts(self) -> int:\n",
    "        return self._pin_attempts\n",
    "\n",
    "    @property\n",
    "    def active_account(self) -> Optional[Account]:\n",
    "        if self._active_card is None:\n",
    "            return None\n",
    "        return self._accounts.get(self._active_card)\n",
    "\n",
    "    # ── Actions ───────────────────────────────────────────────────────────────\n",
    "\n",
    "    def insert_card(self, card_number: str) -> str:\n",
    "        \"\"\"\n",
    "        Insert a card. Transitions IDLE → AWAITING_PIN (or CARD_BLOCKED).\n",
    "\n",
    "        Returns a status message string.\n",
    "        Raises ValueError on bad input; RuntimeError on invalid state transition.\n",
    "        \"\"\"\n",
    "        if not card_number or not isinstance(card_number, str):\n",
    "            raise ValueError(\"card_number must be a non-empty string\")\n",
    "\n",
    "        card_number = card_number.strip()\n",
    "\n",
    "        if self._state != AtmState.IDLE:\n",
    "            raise RuntimeError(\n",
    "                f\"Cannot insert card: machine is {self._state}. Eject current card first.\"\n",
    "            )\n",
    "\n",
    "        account = self._accounts.get(card_number)\n",
    "        if account is None:\n",
    "            # Card not recognised — machine stays IDLE\n",
    "            return f\"Card {card_number!r} not recognised.\"\n",
    "\n",
    "        if account.is_blocked:\n",
    "            self._state = AtmState.CARD_BLOCKED\n",
    "            self._active_card = card_number\n",
    "            return f\"Card {card_number!r} is permanently blocked. Please contact your bank.\"\n",
    "\n",
    "        self._state = AtmState.AWAITING_PIN\n",
    "        self._active_card = card_number\n",
    "        self._pin_attempts = 0\n",
    "        return f\"Card accepted. Please enter your PIN ({self.MAX_PIN_ATTEMPTS} attempts allowed).\"\n",
    "\n",
    "    def enter_pin(self, pin: str) -> str:\n",
    "        \"\"\"\n",
    "        Validate a PIN. Transitions AWAITING_PIN → AUTHENTICATED or CARD_BLOCKED.\n",
    "\n",
    "        Returns a status message string.\n",
    "        Raises ValueError on bad input; RuntimeError on invalid state transition.\n",
    "        \"\"\"\n",
    "        if pin is None or not isinstance(pin, str):\n",
    "            raise ValueError(\"pin must be a string\")\n",
    "\n",
    "        if self._state != AtmState.AWAITING_PIN:\n",
    "            raise RuntimeError(\n",
    "                f\"Cannot enter PIN: machine is {self._state}.\"\n",
    "            )\n",
    "\n",
    "        account = self.active_account\n",
    "        if account is None:\n",
    "            # Defensive guard — should not happen in normal flow\n",
    "            self._state = AtmState.IDLE\n",
    "            self._active_card = None\n",
    "            self._pin_attempts = 0\n",
    "            raise RuntimeError(\"Session corrupt: no active account found. Card ejected.\")\n",
    "\n",
    "        if account.pin == pin:\n",
    "            self._state = AtmState.AUTHENTICATED\n",
    "            self._pin_attempts = 0\n",
    "            return f\"PIN accepted. Welcome, {account.holder_name}.\"\n",
    "\n",
    "        # Wrong PIN\n",
    "        self._pin_attempts += 1\n",
    "        remaining = self.MAX_PIN_ATTEMPTS - self._pin_attempts\n",
    "\n",
    "        if remaining <= 0:\n",
    "            account.is_blocked = True\n",
    "            self._state = AtmState.CARD_BLOCKED\n",
    "            return (\n",
    "                f\"Incorrect PIN. Card blocked after {self.MAX_PIN_ATTEMPTS} failed attempts.\"\n",
    "            )\n",
    "\n",
    "        return f\"Incorrect PIN. {remaining} attempt(s) remaining.\"\n",
    "\n",
    "    def check_balance(self) -> float:\n",
    "        \"\"\"\n",
    "        Return the authenticated account's balance.\n",
    "\n",
    "        Raises RuntimeError if not AUTHENTICATED.\n",
    "        \"\"\"\n",
    "        if self._state != AtmState.AUTHENTICATED:\n",
    "            raise RuntimeError(\n",
    "                f\"Cannot check balance: machine is {self._state}.\"\n",
    "            )\n",
    "        # active_account is guaranteed non-None when AUTHENTICATED\n",
    "        return self.active_account.balance  # type: ignore[union-attr]\n",
    "\n",
    "    def withdraw(self, amount: float) -> str:\n",
    "        \"\"\"\n",
    "        Withdraw cash.\n",
    "\n",
    "        Checks:\n",
    "            1. Machine must be AUTHENTICATED\n",
    "            2. Amount must be a positive, finite number\n",
    "            3. Amount must not exceed single-transaction cap\n",
    "            4. ATM must have enough cash\n",
    "            5. Account must have enough balance\n",
    "\n",
    "        On success: deducts from account and ATM; generates a receipt.\n",
    "        Returns a status message string.\n",
    "        \"\"\"\n",
    "        if self._state != AtmState.AUTHENTICATED:\n",
    "            raise RuntimeError(\n",
    "                f\"Cannot withdraw: machine is {self._state}.\"\n",
    "            )\n",
    "\n",
    "        # ── Data-flow: definition of `amount` as a validated float ────────────\n",
    "        try:\n",
    "            amount = float(amount)\n",
    "        except (TypeError, ValueError):\n",
    "            return \"Invalid amount: must be a number.\"\n",
    "\n",
    "        if amount <= 0 or not (amount == amount):   # NaN check via reflexivity\n",
    "            return \"Invalid amount: must be a positive number.\"\n",
    "\n",
    "        if amount > self.MAX_WITHDRAWAL:\n",
    "            return (\n",
    "                f\"Withdrawal exceeds single-transaction limit of \"\n",
    "                f\"${self.MAX_WITHDRAWAL:,.2f}.\"\n",
    "            )\n",
    "\n",
    "        account = self.active_account  # type: ignore[union-attr]\n",
    "\n",
    "        if self._atm_cash <= 0:\n",
    "            return \"ATM is out of cash. Please visit another location.\"\n",
    "\n",
    "        if amount > self._atm_cash:\n",
    "            return (\n",
    "                f\"ATM only has ${self._atm_cash:,.2f} available. \"\n",
    "                f\"Please request a smaller amount.\"\n",
    "            )\n",
    "\n",
    "        if amount > account.balance:\n",
    "            return (\n",
    "                f\"Insufficient funds. Account balance is ${account.balance:,.2f}.\"\n",
    "            )\n",
    "\n",
    "        # ── Data-flow: `amount` used to mutate balance and atm_cash ──────────\n",
    "        account.balance = round(account.balance - amount, 2)\n",
    "        self._atm_cash = round(self._atm_cash - amount, 2)\n",
    "\n",
    "        # ── Data-flow: `receipt` defined here, stored for later assertion ──────\n",
    "        now = datetime.now()\n",
    "        receipt = (\n",
    "            \"================================\\n\"\n",
    "            \"       TRANSACTION RECEIPT      \\n\"\n",
    "            \"================================\\n\"\n",
    "            f\"Date:    {now.strftime('%Y-%m-%d')}\\n\"\n",
    "            f\"Time:    {now.strftime('%H:%M:%S')}\\n\"\n",
    "            f\"Card:    **** **** **** {account.card_number[-4:]}\\n\"\n",
    "            f\"Holder:  {account.holder_name}\\n\"\n",
    "            \"--------------------------------\\n\"\n",
    "            f\"Drawn:   ${amount:>10,.2f}\\n\"\n",
    "            f\"Balance: ${account.balance:>10,.2f}\\n\"\n",
    "            \"================================\\n\"\n",
    "        )\n",
    "        self.last_receipt = receipt  # data-flow: kill of previous receipt value\n",
    "\n",
    "        return f\"Dispensing ${amount:,.2f}. Take your cash and receipt.\"\n",
    "\n",
    "    def eject_card(self) -> str:\n",
    "        \"\"\"\n",
    "        Eject card and return to IDLE from any state except IDLE.\n",
    "\n",
    "        Raises RuntimeError if already IDLE.\n",
    "        \"\"\"\n",
    "        if self._state == AtmState.IDLE:\n",
    "            raise RuntimeError(\"No card inserted.\")\n",
    "\n",
    "        self._state = AtmState.IDLE\n",
    "        self._active_card = None\n",
    "        self._pin_attempts = 0\n",
    "        return \"Card ejected. Have a great day.\"\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "# HELPERS used across tests\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "\n",
    "def make_atm_with_accounts(atm_cash: float = 10_000.0) -> ATM:\n",
    "    \"\"\"Return a fresh ATM loaded with four test accounts.\"\"\"\n",
    "    atm = ATM(atm_cash=atm_cash)\n",
    "    atm.register_account(Account(\"1111\", \"1234\", \"Emad Fattah\", 2500.00))\n",
    "    atm.register_account(Account(\"2222\", \"5678\", \"Bob Martinez\", 840.50))\n",
    "    atm.register_account(Account(\"3333\", \"9999\", \"Carol Chen\", 12_750.00))\n",
    "    atm.register_account(Account(\"4444\", \"0000\", \"David Kim\", 50.00))\n",
    "    return atm\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "# TEST SUITES\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "\n",
    "class TestStateTransitions(unittest.TestCase):\n",
    "    \"\"\"\n",
    "    ╔══════════════════════════════════════════════════════════════╗\n",
    "    ║  1. STATE TRANSITION TESTING                                  ║\n",
    "    ║                                                              ║\n",
    "    ║  Verifies every edge in the state diagram:                   ║\n",
    "    ║                                                              ║\n",
    "    ║  IDLE ──insert valid──► AWAITING_PIN                         ║\n",
    "    ║  IDLE ──insert blocked─► CARD_BLOCKED                        ║\n",
    "    ║  AWAITING_PIN ──correct PIN──► AUTHENTICATED                 ║\n",
    "    ║  AWAITING_PIN ──3 wrong PINs──► CARD_BLOCKED                 ║\n",
    "    ║  AUTHENTICATED ──eject──► IDLE                               ║\n",
    "    ║  CARD_BLOCKED ──eject──► IDLE                                ║\n",
    "    ║                                                              ║\n",
    "    ║  Also verifies INVALID transitions raise RuntimeError.        ║\n",
    "    ╚══════════════════════════════════════════════════════════════╝\n",
    "    \"\"\"\n",
    "\n",
    "    def setUp(self):\n",
    "        self.atm = make_atm_with_accounts()\n",
    "\n",
    "    # ── Sunny Day ─────────────────────────────────────────────────────────────\n",
    "\n",
    "    def test_ST_SD_01_idle_to_awaiting_pin(self):\n",
    "        \"\"\"SUNNY: Insert a valid card → machine moves to AWAITING_PIN.\"\"\"\n",
    "        msg = self.atm.insert_card(\"1111\")\n",
    "        self.assertEqual(self.atm.state, AtmState.AWAITING_PIN)\n",
    "        self.assertIn(\"PIN\", msg)\n",
    "\n",
    "    def test_ST_SD_02_awaiting_pin_to_authenticated(self):\n",
    "        \"\"\"SUNNY: Correct PIN → machine moves to AUTHENTICATED.\"\"\"\n",
    "        self.atm.insert_card(\"1111\")\n",
    "        msg = self.atm.enter_pin(\"1234\")\n",
    "        self.assertEqual(self.atm.state, AtmState.AUTHENTICATED)\n",
    "        self.assertIn(\"Welcome\", msg)\n",
    "\n",
    "    def test_ST_SD_03_authenticated_to_idle(self):\n",
    "        \"\"\"SUNNY: Eject after authentication → machine returns to IDLE.\"\"\"\n",
    "        self.atm.insert_card(\"1111\")\n",
    "        self.atm.enter_pin(\"1234\")\n",
    "        msg = self.atm.eject_card()\n",
    "        self.assertEqual(self.atm.state, AtmState.IDLE)\n",
    "        self.assertIn(\"ejected\", msg)\n",
    "\n",
    "    def test_ST_SD_04_card_blocked_to_idle(self):\n",
    "        \"\"\"SUNNY: Eject a blocked card → machine returns to IDLE.\"\"\"\n",
    "        self.atm.insert_card(\"1111\")\n",
    "        for _ in range(3):\n",
    "            self.atm.enter_pin(\"wrong\")\n",
    "        self.assertEqual(self.atm.state, AtmState.CARD_BLOCKED)\n",
    "        self.atm.eject_card()\n",
    "        self.assertEqual(self.atm.state, AtmState.IDLE)\n",
    "\n",
    "    def test_ST_SD_05_re_insert_after_session(self):\n",
    "        \"\"\"SUNNY: Full session completes; a second card can be inserted.\"\"\"\n",
    "        self.atm.insert_card(\"1111\")\n",
    "        self.atm.enter_pin(\"1234\")\n",
    "        self.atm.eject_card()\n",
    "        # Now insert a different card\n",
    "        self.atm.insert_card(\"2222\")\n",
    "        self.assertEqual(self.atm.state, AtmState.AWAITING_PIN)\n",
    "\n",
    "    # ── Rainy Day ─────────────────────────────────────────────────────────────\n",
    "\n",
    "    def test_ST_RD_01_insert_card_when_not_idle(self):\n",
    "        \"\"\"RAINY: Inserting a card when machine is not IDLE raises RuntimeError.\"\"\"\n",
    "        self.atm.insert_card(\"1111\")  # now AWAITING_PIN\n",
    "        with self.assertRaises(RuntimeError):\n",
    "            self.atm.insert_card(\"2222\")\n",
    "\n",
    "    def test_ST_RD_02_enter_pin_when_idle(self):\n",
    "        \"\"\"RAINY: Entering PIN when IDLE raises RuntimeError.\"\"\"\n",
    "        with self.assertRaises(RuntimeError):\n",
    "            self.atm.enter_pin(\"1234\")\n",
    "\n",
    "    def test_ST_RD_03_enter_pin_when_authenticated(self):\n",
    "        \"\"\"RAINY: Entering PIN when AUTHENTICATED raises RuntimeError.\"\"\"\n",
    "        self.atm.insert_card(\"1111\")\n",
    "        self.atm.enter_pin(\"1234\")\n",
    "        with self.assertRaises(RuntimeError):\n",
    "            self.atm.enter_pin(\"1234\")\n",
    "\n",
    "    def test_ST_RD_04_eject_when_idle(self):\n",
    "        \"\"\"RAINY: Ejecting when no card inserted raises RuntimeError.\"\"\"\n",
    "        with self.assertRaises(RuntimeError):\n",
    "            self.atm.eject_card()\n",
    "\n",
    "    def test_ST_RD_05_insert_pre_blocked_card(self):\n",
    "        \"\"\"RAINY: Inserting a card that is already blocked → CARD_BLOCKED immediately.\"\"\"\n",
    "        # Pre-block the account externally\n",
    "        self.atm._accounts[\"1111\"].is_blocked = True\n",
    "        self.atm.insert_card(\"1111\")\n",
    "        self.assertEqual(self.atm.state, AtmState.CARD_BLOCKED)\n",
    "\n",
    "    def test_ST_RD_06_withdraw_when_not_authenticated(self):\n",
    "        \"\"\"RAINY: Withdrawal when machine is IDLE raises RuntimeError.\"\"\"\n",
    "        with self.assertRaises(RuntimeError):\n",
    "            self.atm.withdraw(100)\n",
    "\n",
    "    def test_ST_RD_07_check_balance_when_not_authenticated(self):\n",
    "        \"\"\"RAINY: check_balance when machine is IDLE raises RuntimeError.\"\"\"\n",
    "        with self.assertRaises(RuntimeError):\n",
    "            self.atm.check_balance()\n",
    "\n",
    "\n",
    "class TestControlFlow(unittest.TestCase):\n",
    "    \"\"\"\n",
    "    ╔══════════════════════════════════════════════════════════════╗\n",
    "    ║  2. CONTROL FLOW TESTING                                     ║\n",
    "    ║                                                              ║\n",
    "    ║  Exercises every branch of every conditional in the ATM.     ║\n",
    "    ║                                                              ║\n",
    "    ║  Branches covered:                                           ║\n",
    "    ║    insert_card:  valid card / unknown card / already blocked ║\n",
    "    ║    enter_pin:    correct / wrong (partial) / wrong (final)   ║\n",
    "    ║    withdraw:     success / non-numeric / negative / zero /   ║\n",
    "    ║                  over-limit / ATM empty / ATM low /          ║\n",
    "    ║                  account empty / account insufficient        ║\n",
    "    ╚══════════════════════════════════════════════════════════════╝\n",
    "    \"\"\"\n",
    "\n",
    "    def setUp(self):\n",
    "        self.atm = make_atm_with_accounts()\n",
    "\n",
    "    def _authenticate(self, card=\"1111\", pin=\"1234\"):\n",
    "        self.atm.insert_card(card)\n",
    "        self.atm.enter_pin(pin)\n",
    "\n",
    "    # ── Sunny Day ─────────────────────────────────────────────────────────────\n",
    "\n",
    "    def test_CF_SD_01_withdraw_exact_balance(self):\n",
    "        \"\"\"SUNNY: Withdraw entire account balance — both checks pass.\"\"\"\n",
    "        self._authenticate()\n",
    "        msg = self.atm.withdraw(2500.00)\n",
    "        self.assertIn(\"Dispensing\", msg)\n",
    "        self.assertEqual(self.atm.active_account.balance, 0.0)\n",
    "\n",
    "    def test_CF_SD_02_withdraw_partial_balance(self):\n",
    "        \"\"\"SUNNY: Partial withdrawal — account still has funds remaining.\"\"\"\n",
    "        self._authenticate()\n",
    "        self.atm.withdraw(100.00)\n",
    "        self.assertAlmostEqual(self.atm.active_account.balance, 2400.00, places=2)\n",
    "\n",
    "    def test_CF_SD_03_check_balance_branch(self):\n",
    "        \"\"\"SUNNY: check_balance returns correct value (exercises the success branch).\"\"\"\n",
    "        self._authenticate()\n",
    "        balance = self.atm.check_balance()\n",
    "        self.assertEqual(balance, 2500.00)\n",
    "\n",
    "    def test_CF_SD_04_one_wrong_pin_then_correct(self):\n",
    "        \"\"\"SUNNY: One wrong PIN (partial-fail branch) then correct PIN.\"\"\"\n",
    "        self.atm.insert_card(\"1111\")\n",
    "        msg_wrong = self.atm.enter_pin(\"0000\")\n",
    "        self.assertIn(\"2 attempt(s) remaining\", msg_wrong)\n",
    "        self.assertEqual(self.atm.state, AtmState.AWAITING_PIN)\n",
    "        msg_ok = self.atm.enter_pin(\"1234\")\n",
    "        self.assertEqual(self.atm.state, AtmState.AUTHENTICATED)\n",
    "        self.assertIn(\"Welcome\", msg_ok)\n",
    "\n",
    "    def test_CF_SD_05_two_wrong_then_correct(self):\n",
    "        \"\"\"SUNNY: Two wrong PINs (1 remaining branch) then correct PIN.\"\"\"\n",
    "        self.atm.insert_card(\"1111\")\n",
    "        self.atm.enter_pin(\"bad1\")\n",
    "        msg = self.atm.enter_pin(\"bad2\")\n",
    "        self.assertIn(\"1 attempt(s) remaining\", msg)\n",
    "        self.atm.enter_pin(\"1234\")\n",
    "        self.assertEqual(self.atm.state, AtmState.AUTHENTICATED)\n",
    "\n",
    "    # ── Rainy Day ─────────────────────────────────────────────────────────────\n",
    "\n",
    "    def test_CF_RD_01_unknown_card(self):\n",
    "        \"\"\"RAINY: insert_card with unrecognised card — machine stays IDLE.\"\"\"\n",
    "        msg = self.atm.insert_card(\"9999\")\n",
    "        self.assertIn(\"not recognised\", msg)\n",
    "        self.assertEqual(self.atm.state, AtmState.IDLE)\n",
    "\n",
    "    def test_CF_RD_02_three_wrong_pins_blocks_card(self):\n",
    "        \"\"\"RAINY: Three consecutive wrong PINs → CARD_BLOCKED.\"\"\"\n",
    "        self.atm.insert_card(\"1111\")\n",
    "        for _ in range(2):\n",
    "            self.atm.enter_pin(\"bad\")\n",
    "        msg = self.atm.enter_pin(\"bad\")\n",
    "        self.assertEqual(self.atm.state, AtmState.CARD_BLOCKED)\n",
    "        self.assertIn(\"blocked\", msg)\n",
    "        self.assertTrue(self.atm._accounts[\"1111\"].is_blocked)\n",
    "\n",
    "    def test_CF_RD_03_withdraw_non_numeric_string(self):\n",
    "        \"\"\"RAINY: Non-numeric withdrawal → invalid-amount branch.\"\"\"\n",
    "        self._authenticate()\n",
    "        msg = self.atm.withdraw(\"abc\")\n",
    "        self.assertIn(\"Invalid amount\", msg)\n",
    "\n",
    "    def test_CF_RD_04_withdraw_negative_amount(self):\n",
    "        \"\"\"RAINY: Negative amount → guard branch fires.\"\"\"\n",
    "        self._authenticate()\n",
    "        msg = self.atm.withdraw(-50)\n",
    "        self.assertIn(\"Invalid amount\", msg)\n",
    "\n",
    "    def test_CF_RD_05_withdraw_zero(self):\n",
    "        \"\"\"RAINY: Zero amount → guard branch fires.\"\"\"\n",
    "        self._authenticate()\n",
    "        msg = self.atm.withdraw(0)\n",
    "        self.assertIn(\"Invalid amount\", msg)\n",
    "\n",
    "    def test_CF_RD_06_withdraw_over_limit(self):\n",
    "        \"\"\"RAINY: Amount exceeds single-transaction cap ($10,000).\"\"\"\n",
    "        self._authenticate(\"3333\", \"9999\")   # Carol has $12,750\n",
    "        msg = self.atm.withdraw(10_001)\n",
    "        self.assertIn(\"limit\", msg)\n",
    "\n",
    "    def test_CF_RD_07_withdraw_more_than_atm_cash(self):\n",
    "        \"\"\"RAINY: ATM has less cash than requested — ATM-cash guard fires.\"\"\"\n",
    "        atm = ATM(atm_cash=200.0)\n",
    "        atm.register_account(Account(\"5555\", \"1111\", \"Eve Adams\", 5000.0))\n",
    "        atm.insert_card(\"5555\")\n",
    "        atm.enter_pin(\"1111\")\n",
    "        msg = atm.withdraw(500)\n",
    "        self.assertIn(\"ATM only has\", msg)\n",
    "\n",
    "    def test_CF_RD_08_atm_completely_empty(self):\n",
    "        \"\"\"RAINY: ATM has zero cash — out-of-cash guard fires.\"\"\"\n",
    "        atm = ATM(atm_cash=0.0)\n",
    "        atm.register_account(Account(\"5555\", \"1111\", \"Eve Adams\", 5000.0))\n",
    "        atm.insert_card(\"5555\")\n",
    "        atm.enter_pin(\"1111\")\n",
    "        msg = atm.withdraw(100)\n",
    "        self.assertIn(\"out of cash\", msg)\n",
    "\n",
    "    def test_CF_RD_09_withdraw_more_than_account_balance(self):\n",
    "        \"\"\"RAINY: Requested amount exceeds account balance — balance guard fires.\"\"\"\n",
    "        self._authenticate(\"4444\", \"0000\")   # David Kim, $50\n",
    "        msg = self.atm.withdraw(200)\n",
    "        self.assertIn(\"Insufficient funds\", msg)\n",
    "\n",
    "    def test_CF_RD_10_withdraw_non_numeric_none(self):\n",
    "        \"\"\"RAINY: None passed as amount — handled gracefully (no crash).\"\"\"\n",
    "        self._authenticate()\n",
    "        msg = self.atm.withdraw(None)\n",
    "        self.assertIn(\"Invalid amount\", msg)\n",
    "\n",
    "\n",
    "class TestDataFlow(unittest.TestCase):\n",
    "    \"\"\"\n",
    "    ╔══════════════════════════════════════════════════════════════╗\n",
    "    ║  3. DATA FLOW TESTING                                        ║\n",
    "    ║                                                              ║\n",
    "    ║  Traces key variables through define → use → kill paths.     ║\n",
    "    ║                                                              ║\n",
    "    ║  Variables traced:                                           ║\n",
    "    ║    account.balance   — defined on Account; mutated by        ║\n",
    "    ║                        withdraw; read by check_balance       ║\n",
    "    ║    atm._atm_cash     — defined on ATM init; mutated by       ║\n",
    "    ║                        withdraw; checked before dispensing   ║\n",
    "    ║    atm.last_receipt  — undefined (None) initially; defined   ║\n",
    "    ║                        by withdraw success; re-defined by    ║\n",
    "    ║                        a second withdraw (old value killed)  ║\n",
    "    ║    pin_attempts      — reset to 0 on insert; incremented     ║\n",
    "    ║                        per wrong PIN; reset to 0 on success  ║\n",
    "    ╚══════════════════════════════════════════════════════════════╝\n",
    "    \"\"\"\n",
    "\n",
    "    def setUp(self):\n",
    "        self.atm = make_atm_with_accounts()\n",
    "\n",
    "    def _authenticate(self, card=\"1111\", pin=\"1234\"):\n",
    "        self.atm.insert_card(card)\n",
    "        self.atm.enter_pin(pin)\n",
    "\n",
    "    # ── Sunny Day ─────────────────────────────────────────────────────────────\n",
    "\n",
    "    def test_DF_SD_01_balance_defined_and_read(self):\n",
    "        \"\"\"SUNNY: account.balance is defined on creation; readable via check_balance.\"\"\"\n",
    "        # Define → use\n",
    "        self._authenticate()\n",
    "        balance = self.atm.check_balance()  # use\n",
    "        self.assertEqual(balance, 2500.00)\n",
    "\n",
    "    def test_DF_SD_02_balance_defined_mutated_used(self):\n",
    "        \"\"\"SUNNY: account.balance define → withdraw mutates it → check_balance reads updated value.\"\"\"\n",
    "        self._authenticate()\n",
    "        initial = self.atm.check_balance()    # use (pre-mutation)\n",
    "        self.atm.withdraw(400.00)             # mutation (kill of old value, define of new)\n",
    "        updated = self.atm.check_balance()    # use (post-mutation)\n",
    "        self.assertAlmostEqual(updated, initial - 400.00, places=2)\n",
    "\n",
    "    def test_DF_SD_03_atm_cash_decreases_after_withdrawal(self):\n",
    "        \"\"\"SUNNY: atm_cash defined at init; used and killed by withdraw.\"\"\"\n",
    "        initial_cash = self.atm.atm_cash     # use: read before mutation\n",
    "        self._authenticate()\n",
    "        self.atm.withdraw(300.00)            # mutation: kill old, define new\n",
    "        self.assertAlmostEqual(self.atm.atm_cash, initial_cash - 300.00, places=2)\n",
    "\n",
    "    def test_DF_SD_04_receipt_defined_by_withdrawal(self):\n",
    "        \"\"\"SUNNY: last_receipt is None before first withdrawal; defined after it.\"\"\"\n",
    "        self.assertIsNone(self.atm.last_receipt)          # pre-condition (None)\n",
    "        self._authenticate()\n",
    "        self.atm.withdraw(100.00)                         # define receipt\n",
    "        self.assertIsNotNone(self.atm.last_receipt)       # use: receipt now exists\n",
    "        self.assertIn(\"TRANSACTION RECEIPT\", self.atm.last_receipt)\n",
    "\n",
    "    def test_DF_SD_05_receipt_redefined_on_second_withdrawal(self):\n",
    "        \"\"\"SUNNY: Second withdrawal kills the old receipt and defines a new one.\"\"\"\n",
    "        self._authenticate()\n",
    "        self.atm.withdraw(100.00)\n",
    "        first_receipt = self.atm.last_receipt    # capture old value\n",
    "\n",
    "        self.atm.withdraw(50.00)                 # kill first, define second\n",
    "        second_receipt = self.atm.last_receipt   # use new value\n",
    "\n",
    "        self.assertNotEqual(first_receipt, second_receipt)\n",
    "        self.assertIn(\"50.00\", second_receipt)\n",
    "\n",
    "    def test_DF_SD_06_pin_attempts_reset_on_insert(self):\n",
    "        \"\"\"SUNNY: pin_attempts defined as 0 at insert_card (fresh session).\"\"\"\n",
    "        self.atm.insert_card(\"1111\")\n",
    "        self.assertEqual(self.atm.pin_attempts, 0)  # use: should be 0\n",
    "\n",
    "    def test_DF_SD_07_pin_attempts_increment_then_reset_on_success(self):\n",
    "        \"\"\"SUNNY: pin_attempts increments on wrong PIN; killed (reset to 0) on correct PIN.\"\"\"\n",
    "        self.atm.insert_card(\"1111\")\n",
    "        self.atm.enter_pin(\"bad\")          # define: attempts → 1\n",
    "        self.assertEqual(self.atm.pin_attempts, 1)\n",
    "        self.atm.enter_pin(\"1234\")         # kill: attempts reset to 0\n",
    "        self.assertEqual(self.atm.pin_attempts, 0)\n",
    "\n",
    "    def test_DF_SD_08_multiple_withdrawals_accumulate_deductions(self):\n",
    "        \"\"\"SUNNY: Sequential withdrawals compound the balance mutation correctly.\"\"\"\n",
    "        self._authenticate()\n",
    "        self.atm.withdraw(200)   # balance: 2500 → 2300\n",
    "        self.atm.withdraw(300)   # balance: 2300 → 2000\n",
    "        self.atm.withdraw(500)   # balance: 2000 → 1500\n",
    "        self.assertAlmostEqual(self.atm.check_balance(), 1500.00, places=2)\n",
    "        self.assertAlmostEqual(self.atm.atm_cash, 10_000 - 1000, places=2)\n",
    "\n",
    "    # ── Rainy Day ─────────────────────────────────────────────────────────────\n",
    "\n",
    "    def test_DF_RD_01_balance_unchanged_after_failed_withdrawal(self):\n",
    "        \"\"\"RAINY: A failed withdrawal must NOT mutate account.balance.\"\"\"\n",
    "        self._authenticate(\"4444\", \"0000\")   # David Kim, $50\n",
    "        before = self.atm.check_balance()\n",
    "        self.atm.withdraw(500)               # should fail — insufficient funds\n",
    "        after = self.atm.check_balance()\n",
    "        self.assertEqual(before, after)\n",
    "\n",
    "    def test_DF_RD_02_atm_cash_unchanged_after_failed_withdrawal(self):\n",
    "        \"\"\"RAINY: A failed withdrawal must NOT mutate atm_cash.\"\"\"\n",
    "        self._authenticate()\n",
    "        cash_before = self.atm.atm_cash\n",
    "        self.atm.withdraw(-99)               # invalid amount guard fires\n",
    "        self.assertEqual(self.atm.atm_cash, cash_before)\n",
    "\n",
    "    def test_DF_RD_03_receipt_remains_none_after_failed_withdrawal(self):\n",
    "        \"\"\"RAINY: A failed withdrawal must NOT overwrite last_receipt.\"\"\"\n",
    "        self._authenticate(\"4444\", \"0000\")\n",
    "        self.assertIsNone(self.atm.last_receipt)\n",
    "        self.atm.withdraw(5000)              # fails — insufficient funds\n",
    "        self.assertIsNone(self.atm.last_receipt)\n",
    "\n",
    "    def test_DF_RD_04_receipt_preserved_after_second_withdrawal_fails(self):\n",
    "        \"\"\"RAINY: Good receipt followed by a failed withdrawal keeps the good receipt.\"\"\"\n",
    "        self._authenticate()\n",
    "        self.atm.withdraw(100)\n",
    "        good_receipt = self.atm.last_receipt\n",
    "        self.atm.withdraw(99_999)            # fails — over limit\n",
    "        self.assertEqual(self.atm.last_receipt, good_receipt)\n",
    "\n",
    "    def test_DF_RD_05_pin_attempts_accumulate_to_block(self):\n",
    "        \"\"\"RAINY: pin_attempts increments correctly across all 3 failed attempts.\"\"\"\n",
    "        self.atm.insert_card(\"1111\")\n",
    "        self.assertEqual(self.atm.pin_attempts, 0)\n",
    "\n",
    "        self.atm.enter_pin(\"x\")\n",
    "        self.assertEqual(self.atm.pin_attempts, 1)\n",
    "\n",
    "        self.atm.enter_pin(\"x\")\n",
    "        self.assertEqual(self.atm.pin_attempts, 2)\n",
    "\n",
    "        self.atm.enter_pin(\"x\")   # 3rd wrong → card blocked\n",
    "        # After blocking, state is CARD_BLOCKED; attempts stay at 3 (not reset)\n",
    "        self.assertEqual(self.atm.pin_attempts, 3)\n",
    "        self.assertEqual(self.atm.state, AtmState.CARD_BLOCKED)\n",
    "\n",
    "    def test_DF_RD_06_account_created_with_invalid_balance_raises(self):\n",
    "        \"\"\"RAINY: Account.__init__ rejects negative balance — data validated at definition.\"\"\"\n",
    "        with self.assertRaises(ValueError):\n",
    "            Account(\"X\", \"0000\", \"Hacker\", -100)\n",
    "\n",
    "    def test_DF_RD_07_atm_created_with_invalid_cash_raises(self):\n",
    "        \"\"\"RAINY: ATM.__init__ rejects negative cash — data validated at definition.\"\"\"\n",
    "        with self.assertRaises(ValueError):\n",
    "            ATM(atm_cash=-500)\n",
    "\n",
    "    def test_DF_RD_08_insert_card_empty_string_raises(self):\n",
    "        \"\"\"RAINY: insert_card with empty string raises ValueError before state change.\"\"\"\n",
    "        with self.assertRaises(ValueError):\n",
    "            self.atm.insert_card(\"\")\n",
    "        self.assertEqual(self.atm.state, AtmState.IDLE)\n",
    "\n",
    "    def test_DF_RD_09_enter_pin_none_raises(self):\n",
    "        \"\"\"RAINY: enter_pin(None) raises ValueError — input validated at entry point.\"\"\"\n",
    "        self.atm.insert_card(\"1111\")\n",
    "        with self.assertRaises(ValueError):\n",
    "            self.atm.enter_pin(None)\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "# ENTRY POINT\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    print(\"=\" * 70)\n",
    "    print(\"  ATM TESTING DEMO — State Transitions / Control Flow / Data Flow\")\n",
    "    print(\"=\" * 70)\n",
    "    print()\n",
    "\n",
    "    # Run all three suites and collect results\n",
    "    loader = unittest.TestLoader()\n",
    "    suite = unittest.TestSuite()\n",
    "\n",
    "    for cls in [TestStateTransitions, TestControlFlow, TestDataFlow]:\n",
    "        suite.addTests(loader.loadTestsFromTestCase(cls))\n",
    "\n",
    "    runner = unittest.TextTestRunner(verbosity=2)\n",
    "    result = runner.run(suite)\n",
    "\n",
    "    print()\n",
    "    print(\"=\" * 70)\n",
    "    total = result.testsRun\n",
    "    passed = total - len(result.failures) - len(result.errors)\n",
    "    print(f\"  RESULTS: {passed}/{total} tests passed\")\n",
    "    if result.failures or result.errors:\n",
    "        print(\"  FAILURES / ERRORS — see output above\")\n",
    "    else:\n",
    "        print(\"  ALL TESTS PASSED\")\n",
    "    print(\"=\" * 70)\n",
    "\n",
    "\n",
    "# ── Interactive ATM — it asks YOU for the card and PIN ──\n",
    "\n",
    "atm = make_atm_with_accounts()\n",
    "print(\"Welcome to the ATM!\")\n",
    "print(\"-\" * 40)\n",
    "\n",
    "# Step 1: ask for the card number\n",
    "card = input(\"Please insert your card (enter card number): \").strip()\n",
    "print(atm.insert_card(card))\n",
    "\n",
    "# Step 2: ask for the PIN (up to 3 tries)\n",
    "while atm.state == AtmState.AWAITING_PIN:\n",
    "    pin = input(\"Please enter your PIN: \").strip()\n",
    "    print(atm.enter_pin(pin))\n",
    "\n",
    "# Step 3: if PIN was correct, ask what to withdraw\n",
    "if atm.state == AtmState.AUTHENTICATED:\n",
    "    print(f\"Your balance is: ${atm.check_balance():,.2f}\")\n",
    "    amount = float(input(\"How much would you like to withdraw? $\"))\n",
    "    print(atm.withdraw(amount))\n",
    "    if atm.last_receipt:\n",
    "        print()\n",
    "        print(atm.last_receipt)\n",
    "    print(atm.eject_card())\n",
    "elif atm.state == AtmState.CARD_BLOCKED:\n",
    "    print(\"Sorry, your card has been blocked.\")\n",
    "    print(atm.eject_card())\n",
    "else:\n",
    "    print(\"Session ended — card was not accepted.\")\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c6e0afbc-04bf-4687-925f-61893697ff32",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
