# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEMADRecBtq1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_eMADRecBtq1(self):
    self.driver.get("http://localhost:8080/")
    self.driver.set_window_size(1472, 906)
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(2) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary").click()
    self.driver.find_element(By.LINK_TEXT, "Continue Shopping").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(6) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.ID, "quantity").click()
    dropdown = self.driver.find_element(By.ID, "quantity")
    dropdown.find_element(By.XPATH, "//option[. = '2']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#quantity > option:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(3) img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary:nth-child(1)").click()
  
