// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EMADRecBtq1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void eMADRecBtq1() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1472, 906));
    driver.findElement(By.cssSelector(".col-md-4:nth-child(2) .hot-product-card-img-overlay")).click();
    driver.findElement(By.cssSelector(".cymbal-button-primary")).click();
    driver.findElement(By.linkText("Continue Shopping")).click();
    driver.findElement(By.cssSelector(".col-md-4:nth-child(6) .hot-product-card-img-overlay")).click();
    driver.findElement(By.id("quantity")).click();
    {
      WebElement dropdown = driver.findElement(By.id("quantity"));
      dropdown.findElement(By.xpath("//option[. = '2']")).click();
    }
    driver.findElement(By.cssSelector("#quantity > option:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".cymbal-button-primary")).click();
    driver.findElement(By.cssSelector(".col-md-3:nth-child(3) img")).click();
    driver.findElement(By.cssSelector(".cymbal-button-primary")).click();
    driver.findElement(By.cssSelector(".cymbal-button-primary:nth-child(1)")).click();
  }
}
